export const emptyInvoiceBillingInfo = {
  fromStreetAddress: '',
  fromCity: '',
  fromPostCode: '',
  fromCountry: '',
  toClientsName: '',
  toClientsEmail: '',
  toStreetAddress: '',
  toCity: '',
  toPostCode: '',
  toCountry: '',
  invoiceDate: new Date(),
  paymentTerms: '',
  projectDescription: '',
};
